server:
  port: 9101
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: addressdata-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://58.206.97.106:3306/basedata?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Xt2018
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 58.206.97.102:9092,58.206.97.103:9092,58.206.97.104:9092,58.206.97.105:9092
          zk-nodes: 58.206.97.103:2181,58.206.97.104:2181,58.206.97.105:2181
  redis:
    sentinel:
      master: mymaster
      nodes: 58.206.97.107:26379,58.206.97.108:26379
    lettuce:
      pool:
        max-active: 15
        min-idle: 1
        max-idle: 8

#datasource
#dataSource:
#  config: datasource-dev.yml


eureka:
  client:
    service-url:
      defaultZone: http://58.206.97.102:9100/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 58.206.97.104

#2.0新增
management:
  endpoints:
    web:
      exposure:
        include: '*'





