server:
  port: 9102
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: userdata-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test1?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 58.206.97.102:9092,58.206.97.103:9092,58.206.97.104:9092,58.206.97.105:9092
          zk-nodes: 58.206.97.103:2181,58.206.97.104:2181,58.206.97.105:2181


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9100/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: '*'

xtkj:
  biggod: xuebowen