server:
  port: 9101

spring:
  application:
    name: zuul-service


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9100/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

zuul:
  routes:
    api-a:
      path: /user/**
      serviceId: userdata-service
    api-b:
      path: /address/**
      serviceId: addressdata-service

management:
  endpoints:
    web:
      exposure:
        include: '*'